#!/bin/bash

REFRESHRATE=1
LEDCONTROLLER="/usr/bin/ledcontroller"

while (true); do

  for discoColor in blue red green cyan purple yellow white; do

    $LEDCONTROLLER $discoColor

    sleep "$REFRESHRATE"

  done

done
